# Minimal version for standalone ANGLE build
if (NOT HAS_RUN_WEBKIT_COMMON)
    set(HAS_RUN_WEBKIT_COMMON TRUE)
    if (NOT CMAKE_BUILD_TYPE)
        message(WARNING "No CMAKE_BUILD_TYPE value specified, defaulting to RelWithDebInfo.")
        set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "Choose the type of build." FORCE)
    else ()
        message(STATUS "The CMake build type is: ${CMAKE_BUILD_TYPE}")
    endif ()
    set(ALL_PORTS Mac Linux Win)
    set(PORT "NOPORT" CACHE STRING "choose which port to build (one of ${ALL_PORTS})")
    list(FIND ALL_PORTS ${PORT} RET)
    if (${RET} EQUAL -1)
        if (APPLE)
            set(PORT "Mac")
        elseif (UNIX)
            set(PORT "Linux")
        elseif (WIN32)
            set(PORT "Win")
        endif ()
    endif ()
endif ()
